#!/usr/bin/env bash
#prints 1-10 and bad luck and good luck at the correct places
n=1
while (( n <= 10))
do
    if [ $n = 4 ]
    then
        echo "bad luck"
    elif [ $n = 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    n=$(( n+1 ))
done
