#!/usr/bin/env bash
#clock
hour=0
minute=60
while ((hour <= 13))
do
    if [ $minute = 60 ]
    then
        minute=1
        if ((hour != 13))
        then
            echo "Hour: "$hour
        fi
        hour=$((hour+1))
    fi
    if ((hour <= 13))
    then
        echo $minute
    fi
    minute=$((minute+1))
done
